### ISSUE TITLE
Simulation Controls

### ISSUE THREAD

**Issue by kabirsync** [kabirsync/particlegarden#17]
- Pause / Play
- Grain Size (rename)
- FPS
- delta times?
- ticker speed multiple

## Sub-issues to be completed:

- [x] [#18 FPS](https://github.com/kabirsync/particlegarden/issues/18)
- [x] [#19 Grain Size](https://github.com/kabirsync/particlegarden/issues/19)
- [x] [#20 Pause/Play](https://github.com/kabirsync/particlegarden/issues/20)
- [ ] [#21 Ticker Speed](https://github.com/kabirsync/particlegarden/issues/21)
- [ ] [#22 Delta times](https://github.com/kabirsync/particlegarden/issues/22)
